setwd("~/AssessmentsGeneral/DataMiningProject/ReedyIsland")
dir()
tides<-data.frame(read.csv("tides.csv"))
summary(tides)
tides$date<-as.Date(tides$Date.Time, format="%m/%d/%Y")
summary(tides)
tides.median<-with(tides, aggregate(Water.Level, by=list(date), median))
summary(tides.median)
tides.min<-with(tides, aggregate(Water.Level, by=list(date), min))
summary(tides.min)
names(tides.median)<-c("date", "tide.median")
head(tides.median)
names(tides.min)<-c("date", "tide.min")
head(tides.min)
daily.tides<-merge(tides.median, tides.min, by.x="date", by.y="date")
head(daily.tides)
tides.max<-with(tides, aggregate(Water.Level, by=list(date), max))
daily.tides<-merge(tides.median, tides.min, by.x="date", by.y="date")
head(daily.tides)
names(tides.max)<-c("date", "tide.max")
summary(daily.tides)
daily.tides<-merge(daily.tides, tides.max, by.x="date", by.y="date")
head(daily.tides)
daily.tides$range<-daily.tides$tide.max-daily.tides$tide.min
head(daily.tides)
write.table(daily.tides, file="dailytides.csv", sep=",", row.names=FALSE)